[package]
name = "instrumentation-code"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot  = "*"
serde        = { version = "*", features = ["derive", "rc"] }
serde_json   = "*"
erased-serde = "*"
log = "*"
env_logger = "*"
