[package]
name = "instrumentation-code"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot  = "0.12"
serde        = { version = "1.0", features = ["derive", "rc"] }
serde_json   = "1.0"
erased-serde = "0.3"
log = "0.4"
env_logger = "0.9"
